const addressData = [
  { id: 1, city: "Thành phố Hà Nội" },
  { id: 2, city: "Thành phố Huế" },
  { id: 3, city: "Tỉnh Lai Châu" },
  { id: 4, city: "Tỉnh Điện Biên" },
  { id: 5, city: "Tỉnh Sơn La" },
  { id: 6, city: "Tỉnh Lạng Sơn" },
  { id: 7, city: "Tỉnh Quảng Ninh" },
  { id: 8, city: "Tỉnh Thanh Hoá" },
  { id: 9, city: "Tỉnh Nghệ An" },
  { id: 10, city: "Tỉnh Hà Tĩnh" },
  { id: 11, city: "Tỉnh Cao Bằng" },
  { id: 12, city: "Tỉnh Tuyên Quang" },
  { id: 13, city: "Tỉnh Lào Cai" },
  { id: 14, city: "Tỉnh Thái Nguyên" },
  { id: 15, city: "Tỉnh Phú Thọ" },
  { id: 16, city: "Tỉnh Bắc Ninh" },
  { id: 17, city: "Tỉnh Hưng Yên" },
  { id: 18, city: "Thành phố Hải Phòng" },
  { id: 19, city: "Tỉnh Ninh Bình" },
  { id: 20, city: "Tỉnh Quảng Trị" },
  { id: 21, city: "Thành phố Đà Nẵng" },
  { id: 22, city: "Tỉnh Quảng Ngãi" },
  { id: 23, city: "Tỉnh Gia Lai" },
  { id: 24, city: "Tỉnh Khánh Hoà" },
  { id: 25, city: "Tỉnh Lâm Đồng" },
  { id: 26, city: "Tỉnh Đắk Lắk" },
  { id: 27, city: "Thành phố Hồ Chí Minh" },
  { id: 28, city: "Tỉnh Đồng Nai" },
  { id: 29, city: "Tỉnh Tây Ninh" },
  { id: 30, city: "Thành phố Cần Thơ" },
  { id: 31, city: "Tỉnh Vĩnh Long" },
  { id: 32, city: "Tỉnh Đồng Tháp" },
  { id: 33, city: "Tỉnh Cà Mau" },
  { id: 34, city: "Tỉnh An Giang" },
];

export default addressData;
